// data.ts

export const menuItems = [
    {
        id: 1,
        name: 'Classic Margherita',
        price: 12.99,
        category: 'Pizza',
        description: 'Fresh tomato, mozzarella, basil.',
        ratings: 4.5,
        discount: null,
        image:'https://png.pngtree.com/png-vector/20230909/ourmid/pngtree-margherita-pizza-in-a-dish-png-image_10012685.png'
    },
    {
        id: 2,
        name: 'Pepperoni Passion',
        price: 15.99,
        category: 'Pizza',
        description: 'Classic pepperoni slices with melted mozzarella.',
        ratings: 4.7,
        discount: null,
        image:'https://png.pngtree.com/png-vector/20231215/ourlarge/pngtree-a-slice-pepperoni-pizza-clip-art-png-image_11324300.png'
    },
    {
        id: 3,
        name: 'Mediterranean Delight',
        price: 16.99,
        category: 'Pizza',
        description: 'Kalamata olives, feta cheese, cherry tomatoes, and basil.',
        ratings: 4.5,
        discount: 10,
        image:'https://img.freepik.com/premium-photo/mediterranean-meze-delight-transparent-background_894067-17836.jpg'
    },
    {
        id: 4,
        name: 'Supreme Feast',
        price: 17.99,
        category: 'Pizza',
        description: 'A combination of sausage, mushrooms, bell peppers, and onions.',
        ratings: 4.6,
        discount: null,
        image:'https://mymarios.com/pystedod/Meat-Feast-MARIOS2-MJ7094-29.5.2020-online-1.png'
    },
    {
        id: 5,
        name: 'BBQ Chicken Delight',
        price: 18.99,
        category: 'Pizza',
        description: 'Grilled chicken, red onions, BBQ sauce, and cilantro.',
        ratings: 4.8,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/021/665/576/original/delicious-grilled-chicken-cutout-png.png'
    },
    {
        id: 6,
        name: 'Veggie Extravaganza',
        price: 16.99,
        category: 'Pizza',
        description: 'A medley of fresh vegetables like bell peppers, onions, mushrooms, and olives.',
        ratings: 4.4,
        discount: 15,
        image:'https://tatis.my/demo/pizza/wp-content/uploads/2019/01/Product9-1.png'
    },
    {
        id: 7,
        name: 'Hawaiian Paradise',
        price: 15.99,
        category: 'Pizza',
        description: 'Ham, pineapple, and bacon for a tropical twist.',
        ratings: 4.6,
        discount: null,
        image:'https://png.pngtree.com/png-clipart/20231111/original/pngtree-dive-into-the-pineapple-paradise-of-hawaiian-pizza-png-image_13534949.png'
    },
    {
        id: 8,
        name: 'Margherita Deluxe',
        price: 17.99,
        category: 'Pizza',
        description: 'Buffalo mozzarella, cherry tomatoes, and fresh basil leaves.',
        ratings: 4.5,
        discount: null,
        image:'https://png.pngtree.com/png-vector/20230909/ourmid/pngtree-margherita-pizza-in-a-dish-png-image_10012685.png'
    },
    {
        id: 9,
        name: 'White Garlic Pizza',
        price: 14.99,
        category: 'Pizza',
        description: 'Garlic-infused olive oil, ricotta cheese, and spinach.',
        ratings: 4.3,
        discount: 10,
        image:'https://www.pngkit.com/png/detail/215-2154539_cheese-garlic-cheese-and-garlic-pizza.png',
    },
    {
        id: 10,
        name: 'Meat Lovers\' Feast',
        price: 18.99,
        category: 'Pizza',
        description: 'A carnivore\'s dream with pepperoni, sausage, bacon, and ham.',
        ratings: 4.9,
        discount: null,
        image:'https://www.nicepng.com/png/detail/2-23197_mega-meat-pizza-pizza.png'
    },
    {
        id: 11,
        name: 'Classic Cheeseburger',
        price: 9.99,
        category: 'Burger',
        description: 'Juicy beef patty, American cheese, lettuce, tomato, and pickles.',
        ratings: 4.5,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/022/911/684/non_2x/classic-chicken-burger-free-illustration-icon-free-png.png'
    },
    {
        id: 12,
        name: 'BBQ Bacon Burger',
        price: 11.99,
        category: 'Burger',
        description: 'Grilled beef patty, crispy bacon, cheddar cheese, and BBQ sauce.',
        ratings: 4.7,
        discount: 15,
        image: 'https://t4.ftcdn.net/jpg/05/85/29/13/360_F_585291348_nfsxpgUHUkphTWtkruvHW7lGvF6IdSvM.jpg',
    },
    {
        id: 13,
        name: 'Veggie Burger Deluxe',
        price: 10.99,
        category: 'Burger',
        description: 'Vegetarian patty, Swiss cheese, avocado, lettuce, and special sauce.',
        ratings: 4.2,
        discount: null,
        image: 'https://static.vecteezy.com/system/resources/previews/022/598/687/original/tasty-beef-burger-png.png',
    },
    {
        id: 14,
        name: 'Spicy Chicken Burger',
        price: 10.99,
        category: 'Burger',
        description: 'Crispy chicken patty, pepper jack cheese, jalapeños, and spicy mayo.',
        ratings: 4.6,
        discount: null,
        image: 'https://t4.ftcdn.net/jpg/05/61/82/83/360_F_561828375_KCtTuNdpQTjHrMqDrcoCpoLaYhLrZQdI.jpg',
    },
    {
        id: 15,
        name: 'Mushroom Swiss Burger',
        price: 11.99,
        category: 'Burger',
        description: 'Beef patty, Swiss cheese, sautéed mushrooms, and truffle aioli.',
        ratings: 4.4,
        discount: null,
        image: 'https://png.pngtree.com/png-clipart/20230928/original/pngtree-burger-png-images-png-image_13164941.png',
    },
    {
        id: 16,
        name: 'Beyond Meat Burger',
        price: 12.99,
        category: 'Burger',
        description: 'Plant-based patty, vegan cheese, lettuce, tomato, and vegan mayo.',
        ratings: 4.3,
        discount: null,
        image: 'https://t3.ftcdn.net/jpg/06/01/07/12/360_F_601071205_jxLMJzJKNPM1g5ciDuW32Nj8vO5ltNhn.jpg',
    },
    {
        id: 17,
        name: 'Double Bacon Cheeseburger',
        price: 13.99,
        category: 'Burger',
        description: 'Two beef patties, double bacon, American cheese, lettuce, and pickles.',
        ratings: 4.8,
        discount: null,
        image:'https://t3.ftcdn.net/jpg/06/01/07/12/360_F_601071205_jxLMJzJKNPM1g5ciDuW32Nj8vO5ltNhn.jpg'
    },
    {
        id: 18,
        name: 'Avocado Turkey Burger',
        price: 12.99,
        category: 'Burger',
        description: 'Ground turkey patty, avocado, Swiss cheese, lettuce, and cranberry mayo.',
        ratings: 4.5,
        discount: 10,
        image:'https://atlas-content-cdn.pixelsquid.com/stock-images/burger-8d8RmwB-600.jpg'
    },
    {
        id: 19,
        name: 'Chocolate Lava Cake',
        price: 7.99,
        category: 'Dessert',
        description: 'Warm chocolate cake with a gooey molten center, served with vanilla ice cream.',
        ratings: 4.8,
        discount: null,
        image:'https://ifigourmet.com/cdn/shop/products/22g242_1200x1200.png?v=1614894430',
    },
    {
        id: 20,
        name: 'New York Cheesecake',
        price: 8.99,
        category: 'Dessert',
        description: 'Creamy cheesecake with a graham cracker crust, topped with strawberry compote.',
        ratings: 4.6,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/025/065/317/non_2x/cheesecake-with-ai-generated-free-png.png',
    },
    {
        id: 21,
        name: 'Tiramisu',
        price: 9.99,
        category: 'Dessert',
        description: 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
        ratings: 4.7,
        discount: null,
        image:'https://png.pngtree.com/png-vector/20230902/ourmid/pngtree-tiramisu-cake-isolated-png-image_9242463.png',
    },
    {
        id: 22,
        name: 'Fruit Sorbet Trio',
        price: 6.99,
        category: 'Dessert',
        description: 'Refreshing trio of fruit sorbets: mango, raspberry, and lemon.',
        ratings: 4.5,
        discount: 20,
        image:'https://5.imimg.com/data5/ME/QF/GLADMIN-33593898/trio-raspberry-vanilla-and-mango-bar-500x500.png',
    },
    {
        id: 23,
        name: 'Caramel Pecan Brownie Sundae',
        price: 10.99,
        category: 'Dessert',
        description: 'Fudgy brownie topped with caramel sauce, pecans, and a scoop of vanilla ice cream.',
        ratings: 4.9,
        discount: null,
        image:'https://png.pngtree.com/png-clipart/20210613/original/pngtree-browni-dessert-diet-meal-png-image_6404131.jpg',
    },
    {
        id: 24,
        name: 'Classic Mojito',
        price: 6.99,
        category: 'Drinks',
        description: 'Freshly muddled mint, lime, and simple syrup, topped with soda water and ice.',
        ratings: 4.4,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/027/145/860/original/mojito-summer-refreshing-cocktail-with-ice-and-mint-perfect-for-drink-catalog-ai-generated-png.png',
    },
    {
        id: 25,
        name: 'Strawberry Lemonade',
        price: 5.99,
        category: 'Drinks',
        description: 'Sweet and tart lemonade with fresh strawberry puree, served over ice.',
        ratings: 4.6,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/027/243/027/original/strawberry-lemonade-sticker-cool-colors-kawaii-clip-art-illustration-transparent-background-generative-ai-png.png',
    },
    {
        id: 26,
        name: 'Iced Caramel Macchiato',
        price: 7.99,
        category: 'Drinks',
        description: 'Espresso mixed with vanilla syrup, milk, and caramel, poured over ice.',
        ratings: 4.7,
        discount: null,
        image:'https://png.pngitem.com/pimgs/s/529-5290701_caff-macchiato-hd-png-download.png',
    },
    {
        id: 27,
        name: 'Mango Tango Smoothie',
        price: 8.99,
        category: 'Drinks',
        description: 'Blended smoothie with mango, banana, yogurt, and orange juice.',
        ratings: 4.5,
        discount: 15,
        image:'https://png.pngtree.com/png-vector/20230325/ourmid/pngtree-summer-orange-smoothie-png-image_6667736.png',
    },
    {
        id: 28,
        name: 'Green Tea Matcha Latte',
        price: 6.99,
        category: 'Drinks',
        description: 'Creamy matcha green tea latte made with steamed milk.',
        ratings: 4.8,
        discount: null,
        image:'https://www.pngitem.com/pimgs/b/69-690442_green-tea-transparent-images-green-tea-images-png.png',
    },
    {
        id: 29,
        name: 'Pineapple Coconut Cooler',
        price: 7.99,
        category: 'Drinks',
        description: 'Refreshing blend of pineapple juice, coconut cream, and crushed ice.',
        ratings: 4.3,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/027/291/891/original/tropical-cocktail-with-pineapple-coconut-and-umbrella-on-transparent-background-free-png.png',
    },
    {
        id: 30,
        name: 'Cucumber Mint Infused Water',
        price: 3.99,
        category: 'Drinks',
        description: 'Cooling and hydrating water infused with cucumber slices and fresh mint leaves.',
        ratings: 4.9,
        discount: 10,
        image:'https://img.freepik.com/premium-photo/detox-water-with-lemon-lime-cucumber-ginger-mint-ingredients-its-preparation-healthy-food-rich-vitamins-antioxidants_332246-220.jpg',
    },
    {
        id: 31,
        name: 'Chai Tea Latte',
        price: 5.99,
        category: 'Drinks',
        description: 'Spiced black tea with steamed milk and a touch of honey.',
        ratings: 4.6,
        discount: null,
        image:'https://d3gg7p8kl1yfy0.cloudfront.net/Recipe-Detail-Oat_Milk_Latte_2022.jpg',
    },
    {
        id: 32,
        name: 'Blueberry Basil Lemonade',
        price: 6.99,
        category: 'Drinks',
        description: 'Lemonade with blueberry and basil infusion, served over ice.',
        ratings: 4.7,
        discount: null,
        image:'https://www.afarmgirlsdabbles.com/wp-content/uploads/2022/06/blueberry-basil-lemonade_afarmgirlsdabbles_01v.jpg',
    },
    {
        id: 33,
        name: 'Espresso Martini',
        price: 9.99,
        category: 'Drinks',
        description: 'Vodka, coffee liqueur, and freshly brewed espresso shaken with ice.',
        ratings: 4.5,
        discount: null,
        image:'https://simply-delicious-food.com/wp-content/uploads/2023/05/Blackberry-lemonade3.jpg',
    },
    {
        id: 34,
        name: 'Classic Pancake Stack',
        price: 9.99,
        category: 'Breakfast',
        description: 'Fluffy pancakes served with maple syrup and a choice of fresh fruits or bacon.',
        ratings: 4.6,
        discount: null,
        image:'https://pngimg.com/uploads/pancake/pancake_PNG120.png',
    },
    {
        id: 35,
        name: 'Avocado Toast with Poached Eggs',
        price: 12.99,
        category: 'Breakfast',
        description: 'Sourdough toast topped with smashed avocado, poached eggs, and cherry tomatoes.',
        ratings: 4.7,
        discount: null,
        image:'https://static.jow.fr/880x880/recipes/4nBoEEPf2543vg.png',
    },
    {
        id: 36,
        name: 'Vegetarian Omelette',
        price: 11.99,
        category: 'Breakfast',
        description: 'Three-egg omelette with mushrooms, bell peppers, onions, and cheese.',
        ratings: 4.5,
        discount: 10,
        image:'https://pngimg.com/d/omelette_PNG22.png',
    },
    {
        id: 37,
        name: 'Greek Yogurt Parfait',
        price: 7.99,
        category: 'Breakfast',
        description: 'Layered Greek yogurt with granola, mixed berries, and honey drizzle.',
        ratings: 4.8,
        discount: null,
        image:'https://i.pinimg.com/736x/3f/cd/d3/3fcdd350062147e0c18ef7cb40b20721.jpg',
    },
    {
        id: 38,
        name: 'Breakfast Burrito',
        price: 10.99,
        category: 'Breakfast',
        description: 'Flour tortilla filled with scrambled eggs, black beans, cheese, and salsa.',
        ratings: 4.4,
        discount: null,
        image:'https://images.pngnice.com/download/2322/Breakfast-burrito-PNG-HD-Isolated.png',
    },
    {
        id: 39,
        name: 'Butter Chicken',
        price: 15.99,
        category: 'Indian',
        description: 'Tender chicken cooked in a creamy tomato and butter sauce, served with naan.',
        ratings: 3.1,
        discount: null,
        image:'https://static.vecteezy.com/system/resources/previews/025/228/103/original/fresh-indian-butter-chicken-with-rice-isolated-on-transparent-background-png.png',
    },
    {
        id: 40,
        name: 'Chicken Biryani',
        price: 14.99,
        category: 'Indian',
        description: 'Fragrant basmati rice cooked with chicken, aromatic spices, and garnished with fried onions.',
        ratings: 4.7,
        discount: 10,
        image:'https://png.pngtree.com/png-clipart/20230527/original/pngtree-chicken-biryani-top-view-png-image_9171063.png',
    },
    {
        id: 41,
        name: 'Paneer Tikka Masala',
        price: 13.99,
        category: 'Indian',
        description: 'Grilled paneer cubes in a rich and spicy tomato-based curry.',
        ratings: 4.5,
        discount: null,
        image:'https://png.pngtree.com/png-clipart/20230912/original/pngtree-paneer-butter-masala-png-image_11051765.png',
    },
    {
        id: 42,
        name: 'Vegetable Samosa',
        price: 8.99,
        category: 'Indian',
        description: 'Crispy pastry filled with spiced potatoes, peas, and herbs, served with chutney.',
        ratings: 4.6,
        discount: null,
        image:'https://img.pikbest.com/origin/09/19/91/64UpIkbEsT6m5.png!sw800',
    },
    {
        id: 43,
        name: 'Dal Makhani',
        price: 12.99,
        category: 'Indian',
        description: 'Slow-cooked black lentils and kidney beans in a creamy tomato sauce.',
        ratings: 4.4,
        discount: null,
        image:'https://t4.ftcdn.net/jpg/01/84/58/83/360_F_184588398_RczrKKQfy5GZWSd1rvCYu6GEPlsCd9rv.jpg',
    },
    { 
        id: 44,
        name: 'Aloo Gobi',
        price: 11.99,
        category: 'Indian',
        description: 'Stir-fried cauliflower and potatoes with Indian spices.',
        ratings: 4.3,
        discount: null,
        image:'https://www.pngitem.com/pimgs/m/317-3177451_aloo-gobi-png-download-transparent-png.png',
    },
    {
        id: 45,
        name: 'Chana Masala',
        price: 10.99,
        category: 'Indian',
        description: 'Chickpeas cooked in a flavorful tomato-based curry.',
        ratings: 4.6,
        discount: 15,
        image:'https://img.freepik.com/premium-photo/spicy-chickpea-curry-chana-masala-choley-bowl-with-chapati-salad-traditional-north-indian-dish_466689-6355.jpg',
    },
    {
        id: 46,
        name: 'Tandoori Chicken',
        price: 16.99,
        category: 'Indian',
        description: 'Marinated chicken skewers grilled to perfection in a tandoor.',
        ratings: 4.9,
        discount: null,
        image:'https://www.pngitem.com/pimgs/m/119-1192275_tandoori-chicken-plate-png-transparent-png.png',
      },
];

export const menuOptions = [
    // Sauce Options
    {
      Optionid: 1,
      OptionName: 'Sauce',
      MultipleSelection: true,
      type: 'Sauce',
      items: [
        { name: 'Garlic Sauce', price: 2.00 },
        { name: 'Tomato Sauce', price: 2.00 },
        { name: 'Spicy Marinara', price: 2.00 },
        { name: 'Pesto Sauce', price: 2.00 },
        { name: 'Alfredo Sauce', price: 2.00 },
      ],
    },
  
    // Drinks
    {
      Optionid: 2,
      OptionName: 'Drink',
      MultipleSelection: true,
      type: 'Drinks',
      items: [
        { name: 'Coca-Cola', price: 2.00 },
        { name: 'Sprite', price: 2.00 },
        { name: 'Iced Tea', price: 2.00 },
        { name: 'Orange Juice', price: 2.00 },
        { name: 'Lemonade', price: 2.00 },
      ],
    },
  
    // Desserts
    {
      Optionid: 3,
      OptionName: 'Dessert',
      type: 'Dessert',
      MultipleSelection: false,
      items: [
        { name: 'Chocolate Lava Cake', price: 3.00 },
        { name: 'New York Cheesecake', price: 3.00 },
        { name: 'Tiramisu', price: 3.00 },
        { name: 'Fruit Sorbet Trio', price: 3.00 },
        { name: 'Caramel Pecan Brownie Sundae', price: 3.00 },
      ],
    },
  
    // Additional Options
    {
      Optionid: 4,
      OptionName: 'Custom Option 1',
      MultipleSelection: true,
      items: [
        { name: 'Custom Item 1', price: 5.00 },
        { name: 'Custom Item 2', price: 6.00 },
        { name: 'Custom Item 3', price: 4.50 },
        { name: 'Custom Item 4', price: 7.50 },
        { name: 'Custom Item 5', price: 5.50 },
      ],
    },
    {
      Optionid: 5,
      OptionName: 'Custom Option 2',
      MultipleSelection: true,
      items: [
        { name: 'Custom Item 6', price: 8.00 },
        { name: 'Custom Item 7', price: 5.50 },
        { name: 'Custom Item 8', price: 4.00 },
        { name: 'Custom Item 9', price: 6.50 },
        { name: 'Custom Item 10', price: 7.00 },
      ],
    },
    // ... Add more options as needed
  ];