// data.ts

export const menuItems = [
    {
        name: 'Classic Margherita',
        price: 12.99,
        category: 'Pizza',
        description: 'Fresh tomato, mozzarella, basil.',
        ratings: 4.5,
        discount: null,
    },
    {
        name: 'Pepperoni Passion',
        price: 15.99,
        category: 'Pizza',
        description: 'Classic pepperoni slices with melted mozzarella.',
        ratings: 4.7,
        discount: null,
    },
    {
        name: 'Mediterranean Delight',
        price: 16.99,
        category: 'Pizza',
        description: 'Kalamata olives, feta cheese, cherry tomatoes, and basil.',
        ratings: 4.5,
        discount: 10,
    },
    {
        name: 'Supreme Feast',
        price: 17.99,
        category: 'Pizza',
        description: 'A combination of sausage, mushrooms, bell peppers, and onions.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'BBQ Chicken Delight',
        price: 18.99,
        category: 'Pizza',
        description: 'Grilled chicken, red onions, BBQ sauce, and cilantro.',
        ratings: 4.8,
        discount: null,
    },
    {
        name: 'Veggie Extravaganza',
        price: 16.99,
        category: 'Pizza',
        description: 'A medley of fresh vegetables like bell peppers, onions, mushrooms, and olives.',
        ratings: 4.4,
        discount: 15,
    },
    {
        name: 'Hawaiian Paradise',
        price: 15.99,
        category: 'Pizza',
        description: 'Ham, pineapple, and bacon for a tropical twist.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'Margherita Deluxe',
        price: 17.99,
        category: 'Pizza',
        description: 'Buffalo mozzarella, cherry tomatoes, and fresh basil leaves.',
        ratings: 4.5,
        discount: null,
    },
    {
        name: 'White Garlic Pizza',
        price: 14.99,
        category: 'Pizza',
        description: 'Garlic-infused olive oil, ricotta cheese, and spinach.',
        ratings: 4.3,
        discount: 10,
    },
    {
        name: 'Meat Lovers\' Feast',
        price: 18.99,
        category: 'Pizza',
        description: 'A carnivore\'s dream with pepperoni, sausage, bacon, and ham.',
        ratings: 4.9,
        discount: null,
    },
    {
        name: 'Classic Cheeseburger',
        price: 9.99,
        category: 'Burger',
        description: 'Juicy beef patty, American cheese, lettuce, tomato, and pickles.',
        ratings: 4.5,
        discount: null,
        image:'/src/assets/Image/Burger/00.png'
    },
    {
        name: 'BBQ Bacon Burger',
        price: 11.99,
        category: 'Burger',
        description: 'Grilled beef patty, crispy bacon, cheddar cheese, and BBQ sauce.',
        ratings: 4.7,
        discount: 15,
    },
    {
        name: 'Veggie Burger Deluxe',
        price: 10.99,
        category: 'Burger',
        description: 'Vegetarian patty, Swiss cheese, avocado, lettuce, and special sauce.',
        ratings: 4.2,
        discount: null,
    },
    {
        name: 'Spicy Chicken Burger',
        price: 10.99,
        category: 'Burger',
        description: 'Crispy chicken patty, pepper jack cheese, jalapeños, and spicy mayo.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'Mushroom Swiss Burger',
        price: 11.99,
        category: 'Burger',
        description: 'Beef patty, Swiss cheese, sautéed mushrooms, and truffle aioli.',
        ratings: 4.4,
        discount: null,
    },
    {
        name: 'Beyond Meat Burger',
        price: 12.99,
        category: 'Burger',
        description: 'Plant-based patty, vegan cheese, lettuce, tomato, and vegan mayo.',
        ratings: 4.3,
        discount: null,
    },
    {
        name: 'Double Bacon Cheeseburger',
        price: 13.99,
        category: 'Burger',
        description: 'Two beef patties, double bacon, American cheese, lettuce, and pickles.',
        ratings: 4.8,
        discount: null,
    },
    {
        name: 'Avocado Turkey Burger',
        price: 12.99,
        category: 'Burger',
        description: 'Ground turkey patty, avocado, Swiss cheese, lettuce, and cranberry mayo.',
        ratings: 4.5,
        discount: 10,
    },
    {
        name: 'Chocolate Lava Cake',
        price: 7.99,
        category: 'Dessert',
        description: 'Warm chocolate cake with a gooey molten center, served with vanilla ice cream.',
        ratings: 4.8,
        discount: null,
    },
    {
        name: 'New York Cheesecake',
        price: 8.99,
        category: 'Dessert',
        description: 'Creamy cheesecake with a graham cracker crust, topped with strawberry compote.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'Tiramisu',
        price: 9.99,
        category: 'Dessert',
        description: 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
        ratings: 4.7,
        discount: null,
    },
    {
        name: 'Fruit Sorbet Trio',
        price: 6.99,
        category: 'Dessert',
        description: 'Refreshing trio of fruit sorbets: mango, raspberry, and lemon.',
        ratings: 4.5,
        discount: 20,
    },
    {
        name: 'Caramel Pecan Brownie Sundae',
        price: 10.99,
        category: 'Dessert',
        description: 'Fudgy brownie topped with caramel sauce, pecans, and a scoop of vanilla ice cream.',
        ratings: 4.9,
        discount: null,
    },
    {
        name: 'Classic Mojito',
        price: 6.99,
        category: 'Drinks',
        description: 'Freshly muddled mint, lime, and simple syrup, topped with soda water and ice.',
        ratings: 4.4,
        discount: null,
    },
    {
        name: 'Strawberry Lemonade',
        price: 5.99,
        category: 'Drinks',
        description: 'Sweet and tart lemonade with fresh strawberry puree, served over ice.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'Iced Caramel Macchiato',
        price: 7.99,
        category: 'Drinks',
        description: 'Espresso mixed with vanilla syrup, milk, and caramel, poured over ice.',
        ratings: 4.7,
        discount: null,
    },
    {
        name: 'Mango Tango Smoothie',
        price: 8.99,
        category: 'Drinks',
        description: 'Blended smoothie with mango, banana, yogurt, and orange juice.',
        ratings: 4.5,
        discount: 15,
    },
    {
        name: 'Green Tea Matcha Latte',
        price: 6.99,
        category: 'Drinks',
        description: 'Creamy matcha green tea latte made with steamed milk.',
        ratings: 4.8,
        discount: null,
    },
    {
        name: 'Pineapple Coconut Cooler',
        price: 7.99,
        category: 'Drinks',
        description: 'Refreshing blend of pineapple juice, coconut cream, and crushed ice.',
        ratings: 4.3,
        discount: null,
    },
    {
        name: 'Cucumber Mint Infused Water',
        price: 3.99,
        category: 'Drinks',
        description: 'Cooling and hydrating water infused with cucumber slices and fresh mint leaves.',
        ratings: 4.9,
        discount: 10,
    },
    {
        name: 'Chai Tea Latte',
        price: 5.99,
        category: 'Drinks',
        description: 'Spiced black tea with steamed milk and a touch of honey.',
        ratings: 4.6,
        discount: null,
    },
    {
        name: 'Blueberry Basil Lemonade',
        price: 6.99,
        category: 'Drinks',
        description: 'Lemonade with blueberry and basil infusion, served over ice.',
        ratings: 4.7,
        discount: null,
    },
    {
        name: 'Espresso Martini',
        price: 9.99,
        category: 'Drinks',
        description: 'Vodka, coffee liqueur, and freshly brewed espresso shaken with ice.',
        ratings: 4.5,
        discount: null,
    },
    {
        name: 'Classic Pancake Stack',
        price: 9.99,
        category: 'Breakfast',
        description: 'Fluffy pancakes served with maple syrup and a choice of fresh fruits or bacon.',
        ratings: 4.6,
        discount: null,
      },
      {
        name: 'Avocado Toast with Poached Eggs',
        price: 12.99,
        category: 'Breakfast',
        description: 'Sourdough toast topped with smashed avocado, poached eggs, and cherry tomatoes.',
        ratings: 4.7,
        discount: null,
      },
      {
        name: 'Vegetarian Omelette',
        price: 11.99,
        category: 'Breakfast',
        description: 'Three-egg omelette with mushrooms, bell peppers, onions, and cheese.',
        ratings: 4.5,
        discount: 10,
      },
      {
        name: 'Greek Yogurt Parfait',
        price: 7.99,
        category: 'Breakfast',
        description: 'Layered Greek yogurt with granola, mixed berries, and honey drizzle.',
        ratings: 4.8,
        discount: null,
      },
      {
        name: 'Breakfast Burrito',
        price: 10.99,
        category: 'Breakfast',
        description: 'Flour tortilla filled with scrambled eggs, black beans, cheese, and salsa.',
        ratings: 4.4,
        discount: null,
      },
      {
        name: 'Butter Chicken',
        price: 15.99,
        category: 'Indian',
        description: 'Tender chicken cooked in a creamy tomato and butter sauce, served with naan.',
        ratings: 3.1,
        discount: null,
      },
      {
        name: 'Chicken Biryani',
        price: 14.99,
        category: 'Indian',
        description: 'Fragrant basmati rice cooked with chicken, aromatic spices, and garnished with fried onions.',
        ratings: 4.7,
        discount: 10,
      },
      {
        name: 'Paneer Tikka Masala',
        price: 13.99,
        category: 'Indian',
        description: 'Grilled paneer cubes in a rich and spicy tomato-based curry.',
        ratings: 4.5,
        discount: null,
      },
      {
        name: 'Vegetable Samosa',
        price: 8.99,
        category: 'Indian',
        description: 'Crispy pastry filled with spiced potatoes, peas, and herbs, served with chutney.',
        ratings: 4.6,
        discount: null,
      },
      {
        name: 'Dal Makhani',
        price: 12.99,
        category: 'Indian',
        description: 'Slow-cooked black lentils and kidney beans in a creamy tomato sauce.',
        ratings: 4.4,
        discount: null,
      },
      {
        name: 'Aloo Gobi',
        price: 11.99,
        category: 'Indian',
        description: 'Stir-fried cauliflower and potatoes with Indian spices.',
        ratings: 4.3,
        discount: null,
      },
      {
        name: 'Chana Masala',
        price: 10.99,
        category: 'Indian',
        description: 'Chickpeas cooked in a flavorful tomato-based curry.',
        ratings: 4.6,
        discount: 15,
      },
      {
        name: 'Tandoori Chicken',
        price: 16.99,
        category: 'Indian',
        description: 'Marinated chicken skewers grilled to perfection in a tandoor.',
        ratings: 4.9,
        discount: null,
      },
];